### Curso de imágenes - Especialidad I (2018) - FAMAF-UNC

**Alumna: L. Fischer**

# Trabajo practico nº 7

In [1]:
%matplotlib inline

from matplotlib import pyplot as plt
import numpy as np

## Ejercicio 1:
Realizar una simulación determinista de la formación de la imagen por contraste de absorción de un cilindro de agua de 10 cm de diámetro y **altura** irradiado con un haz paralelo de fotones de 50 keV y tamaño de campo de 10 cm × 10 cm. (Detección ideal). Graficar perfil central de la imagen e interpretarlo en términos de las propiedades fı́sicas.

**como esta cilindro respecto del haz**

*Esto se puede ver en el plano x-y siendo z el que pasa por el eje del cilindro.*
*TEngo un haz paralelo de energía fija que incide en el cirdulo de radio 5 cm.*

In [9]:
E0= 50 
detector = np.zeros([24,20])  # para probar la primera vez tomo "pixeles de 0.5 cm"

#Resuelvo en un plano: centro el cilindro en el medio de la matriz 11-12

detector[11,:] = 1
detector[12,:] = 1

print(detector)



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

## Ejercicio 2:
Repetir el ejercicio del item anterior para un haz incidente de 2 canales
energéticos igualmente probables de 50 keV y 30 keV. Analizar y discutir
los resultados obtenidos.

## Ejercicio 3:
Realizar una simulación Monte Carlo análoga al primer item. Analizar los
resultados.

## Ejercicio 4:
Simular un set up experimental tı́pico del instrumento de laboratorio.